import { notFound } from "next/navigation";
import { SimulatorReport } from "@/types/report";
import ScoreGauge from "@/components/report/ScoreGauge";
import DollarHighlights from "@/components/report/DollarHighlights";
import DimensionBars from "@/components/report/DimensionBars";
import UseCasePills from "@/components/report/UseCasePills";
import InsightBlock from "@/components/report/InsightBlock";
import CTASection from "@/components/report/CTASection";

async function fetchReport(slug: string): Promise<SimulatorReport | null> {
  try {
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? "http://localhost:3000";
    const res = await fetch(`${baseUrl}/api/report/${slug}`, { cache: "no-store" });
    if (!res.ok) return null;
    return res.json();
  } catch {
    return null;
  }
}

export default async function ReportPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const report = await fetchReport(slug);

  if (!report) notFound();

  return (
    <main className="min-h-screen bg-gray-950 py-12 px-4">
      <div className="max-w-2xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center">
          <ScoreGauge
            score={report.overall_score}
            tier={report.score_tier}
            companyName={report.company_name}
          />
          <p className="text-gray-500 text-sm mt-3">
            {report.industry} · {report.hq_country} · {report.employee_band} employees · {report.revenue_range}
          </p>
        </div>

        {/* Dollar highlights */}
        <DollarHighlights
          revenueUnlock={report.revenue_unlock_usd}
          costSavings={report.cost_savings_usd}
          timeToLive={report.time_to_live_weeks}
        />

        {/* Dimension bars */}
        <DimensionBars dimensions={report.dimensions} />

        {/* Use cases */}
        <UseCasePills useCases={report.top_use_cases} />

        {/* Insight + gap */}
        <InsightBlock keyInsight={report.key_insight} primaryGap={report.primary_gap} />

        {/* CTAs + email capture + confidence */}
        <CTASection report={report} slug={slug} />

        <p className="text-center text-xs text-gray-800">
          Report generated by Allium Stablecoin Readiness Engine · {new Date().toLocaleDateString()}
        </p>
      </div>
    </main>
  );
}
